---
intf_sriov: |-
  {%- set intf_sriov = sys_intf_mappings["tenant"]["interface"] %}
  {%- if sys_intf_mappings["tenant"]["vlan_tag"] | int %}
  {%- set intf_sriov = intf_sriov + '.' + sys_intf_mappings["tenant"]["vlan_tag"]|string %}
  {%- endif %}
  {{- intf_sriov }}

LOCAL_REPOSITORY_IP: "192.168.137.222"
