##############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- hosts: all
  remote_user: root
  gather_facts: true
  roles:
    - pre-openstack
    - setup-kolla-network
    - storage

- hosts: localhost 
  remote_user: root
  gather_facts: true
  roles:
    - config-kolla
    - pre-deploy
    - kolla-deploy
