# #############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
# #############################################################################
---
- name: Deploy kolla
  shell: "kolla-ansible deploy -i  /opt/kolla-ansible/multinode \
           | tee /var/log/kolla/kolla-deploy.log"

- name: Generate the openrc
  shell: "kolla-ansible post-deploy"
